(define (parrot-speed parrot-type num-coconuts voltage nailed)
    (define (base-speed) 12.0)
    (lambda ()
            (raise 'Should-be-unreachable)) ; '))
)

(define (new-parrot parrot . parameters)
    (apply parrot parameters)
)

(define (european-parrot)
    (define (base-speed) 12.0)
    (lambda () (base-speed))
)

(define (african-parrot num-coconuts)
    (define (base-speed) 12.0)
    (define (load-factor) 9.0)
    (lambda () (max 0.0 (- (base-speed) (* (load-factor) num-coconuts))))
)

(define (norwegian-blue-parrot voltage nailed)
    (define (base-speed) 12.0)
    (define (compute-base-speed-for-voltage voltage)
        (min 24.0 (* voltage (base-speed))))
    (lambda () (if nailed 0.0 (compute-base-speed-for-voltage voltage)))
)
